services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=application/app.py
      - FLASK_ENV=production
    ports:
      - "3000:5000"
    volumes:
      - .:/api-flask
    command: flask run
