[default]
MONGO_DATABASE_URI='mongodb://INTEGRATIONS_CORE:INTEGRATIONS_CORE@localhost:27017'
ZEEV_BASE_URL=''
ZEEV_EMAIL_LOGIN=''
ZEEV_PASSWORD_LOGIN=''
ZEEV_NEW_CLIENT_FLOW_ID=176
CLICKSIGN_BASE_URL=''
CLICKSIGN_TOKEN=''
MONGO_DATABASE_NAME='INTEGRATIONS_CORE'
MONGO_DATABASE_PASSWORD='INTEGRATIONS_CORE'
JGV_EMAIL='contato@yunofp.com.br'
JGV_NAME='JGV Finanças Pessoais Ltda'
JGV_PHONE='62993382611'
CONTRACTS_PROCESSING_DAYS_INTERVAL=5